# config.yml

model_type:
  cddpm
# mdoel args
model:
  width: 32
  height: 32
  channel: 1
  time_dim: 256
  label_dim: 10
  noise_steps: 400
  beta_start: 0.0001
  beta_end: 0.02
  device: cuda

traininng:
  batch_size: 16              
  epochs: 1000          
  learning_rate: 0.0001   
  optimizer: Adam              
  weight_decay: 0
  clip_max_norm: 0.5
  factor: 0.3
  patience: 15         
  device: cuda

dataset_type:
  image_generation
dataset:
  target_width: 32
  target_height: 32
  train_data_path: mnist_train/train.jsonl
  test_data_path: mnist_train/test.jsonl
  valid_data_path: mnist_train/val.jsonl


logging:
  eval_interval: 10     
  save_dir: "./saved_model/cddpm"   