# config.yml

model_type:
  diffusion
# mdoel args
model:
  width: 32
  height: 32
  channel: 3
  time_dim: 32
  noise_steps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  device: cuda

traininng:
  batch_size: 2               
  epochs: 1000          
  learning_rate: 0.0001   
  optimizer: Adam              
  weight_decay: 0.1
  clip_max_norm: 0.5
  factor: 0.3
  patience: 15         
  device: cuda

dataset_type:
  image_generation
dataset:
  target_width: 32
  target_height: 32
  train_data_path: mnist_train/train.jsonl
  test_data_path: mnist_train/test.jsonl
  valid_data_path: mnist_train/val.jsonl


logging:
  log_interval: 100             
  save_dir: "./saved_model/diffusion"   